version: "3.1"

volumes:
  data:

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - PUMA_WORKERS=2
      - RACK_ENV=development
      - RAILS_ENV=development
